name: moprog
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  get_it: ^8.2.0
  dio: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^6.3.0 # Jangan di upgrade Okeh
  freezed_annotation: ^3.1.0
  go_router: ^16.2.0
  fluttertoast: ^8.2.12
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.11.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/