name: moprog
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  get_it: ^8.2.0
  dio: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/